# Generated by Django 5.0.6 on 2024-06-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
