# Generated by Django 5.0.6 on 2024-07-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0003_remove_staffissuedbook_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffissuedbook',
            name='isbn',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentissuedbook',
            name='isbn',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
