# Generated by Django 5.0.6 on 2024-07-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0004_staffissuedbook_isbn_studentissuedbook_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffissuedbook',
            name='isbn',
        ),
    ]
