# Generated by Django 5.0.6 on 2024-07-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_app', '0006_staffissuedbook_fine_studentissuedbook_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffissuedbook',
            name='isbn',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
